### ISSUE TITLE
Prevent workflow from running when creating the repository for the first time

### ISSUE THREAD

**Issue by nicola-corbellini** [cheshire-cat-ai/plugin-template#2]
**Describe the bug**
When creating a new repo from the template the workflow should not be run to avoid creating a tag with the sample code.

**Comment by zAlweNy26** [comment]
I'll try to fix that.

**Comment by zAlweNy26** [comment]
I think it's not possible, but I'll continue searching for a workaround

**Comment by EugenioPetulla** [comment]
I suggest to create a condition in the workflow based on the presence of a file we can name `prevent_workflow`. We can easily delete the file in the `setup.py` script or just tell people to delete it if they want to start the pipeline.

Another way to achieve this can be using some github env vars, but it can be tricky because we have to explain to people how to set them.

## PoC

```
name: Create Release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    tags:
      - "*.*.*"

permissions:
  contents: write
  pull-requests: write

env:
  PLUGIN_JSON: "0.0.1"
  TAG_EXISTS: false

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check for prevent_workflow file
        run: |
          if [[ -f prevent_workflow ]]; then
            echo "prevent_workflow file found. Workflow will not run."
            exit 0
          fi
      - name: Get plugin version
        run: |
          echo 'PLUGIN_JSON<<EOF' >> $GITHUB_ENV
          cat ./plugin.json >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Publish tag
        if: env.TAG_EXISTS == false
        uses: rickstaa/action-create-tag@v1
        with:
          tag: "${{fromJson(env.PLUGIN_JSON).version}}"
          tag_exists_error: false
          message: "Latest release"
      - name: Zip release
        uses: TheDoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'my_plugin.zip'
          exclusions: '*.git* setup.py'
          directory: '.'
          path: '.'
      - name: Upload release
        uses: ncipollo/release-action@v1.12.0
        with:
          tag: "${{fromJson(env.PLUGIN_JSON).version}}"
          artifacts: 'my_plugin.zip'
          allowUpdates: true
          replacesArtifacts: true
          body: |
            ${{ github.event.head_commit.message }}
          token: ${{ secrets.GITHUB_TOKEN }}
```
